#!/bin/bash
yum update -y
yum install httpd -y
service httpd start
chkconfig httpd on
cd /var/www/html
echo "Welcome to my channel webserver-1" >index.html
yum install httpd -y
service httpd start
chkconfig httpd on
cd /var/www/html
